version: "3"

services:

  vsftpd:
    build: .
    restart: always
    ports:
      - "20:20"
      - "21:21"
      - "21100-21109:21100-21109"
    environment:
      FTP_PASV_ADDRESS: '127.0.0.1'
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
